// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// CATEGORIES
export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const POST_NEW_CATEGORIE_START = "POST_NEW_CATEGORIE_START";
export const POST_NEW_CATEGORIE_FAIL = "POST_NEW_CATEGORIE_FAIL";
export const POST_NEW_CATEGORIE_SUCCESS = "POST_NEW_CATEGORIE_SUCCESS";

export const DELETE_CATEGORIE = "DELETE_CATEGORIE";

export const GET_CATEGORIE_PRODUCTS_START = "GET_CATEGORIE_PRODUCTS_START";
export const GET_CATEGORIE_PRODUCTS_FAIL = "GET_CATEGORIE_PRODUCTS_FAIL";
export const GET_CATEGORIE_PRODUCTS_SUCCESS = "GET_CATEGORIE_PRODUCTS_SUCCESS";
export const GET_CATEGORIE_PRODUCTS_FILTER = "GET_CATEGORIE_PRODUCTS_FILTER";
export const GET_MORE_CATEGORIE_PRODUCTS = "GET_MORE_CATEGORIE_PRODUCTS";

// PRODUCTS
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const LOAD_MORE_PRODUCTS = "GET_MORE_PRODUCTS";

export const GET_PRODUCT_DETAILS_START = "GET_PRODUCT_DETAILS_START";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";

export const POST_NEW_PRODUCT_START = "POST_NEW_PRODUCT_START";
export const POST_NEW_PRODUCT_FAIL = "POST_NEW_PRODUCT_FAIL";
export const POST_NEW_PRODUCT_SUCCESS = "POST_NEW_PRODUCT_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_QUERY_FILTER = "SET_QUERY_FILTER";

// CART
export const GET_CART_START = "GET_CART_START";
export const GET_CART_FAIL = "GET_CART_FAIL";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const UPDATE_CART = "UPDATE_CART";

// WISHLISTS
export const GET_WISHLIST_START = "GET_WISHLIST_START";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";

export const ADD_TO_WISHLIST_START = "ADD_TO_WISHLIST_START";
export const ADD_TO_WISHLIST_FAIL = "ADD_TO_WISHLIST_FAIL";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";

export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

// ORDERS
export const GET_USER_ORDERS_START = "GET_USER_ORDERS_START";
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";

export const GET_ORDER_DETAILS_START = "GET_ORDER_DETAILS_START";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL";

export const GET_ADMIN_ORDERS_START = "GET_ADMIN_ORDERS_START";
export const GET_ADMIN_ORDERS_FAIL = "GET_ADMIN_ORDERS_FAIL";
export const GET_ADMIN_ORDERS_SUCCESS = "GET_ADMIN_ORDERS_SUCCESS";

export const CREATE_NEW_ORDER_START = "CREATE_NEW_ORDER_START";
export const CREATE_NEW_ORDER_FAIL = "CREATE_NEW_ORDER_FAIL";
export const CREATE_NEW_ORDER_SUCCESS = "CREATE_NEW_ORDER_SUCCESS";

export const UPDATE_ORDER_START = "UPDATE_ORDER_START";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";

// PROFILE
export const CREATE_OR_UPDATE_PROFILE_START = "CREATE_OR_UPDATE_PROFILE_START";
export const CREATE_OR_UPDATE_PROFILE_SUCCESS = "CREATE_OR_UPDATE_PROFILE_SUCCESS";
export const CREATE_OR_UPDATE_PROFILE_FAIL = "CREATE_OR_UPDATE_PROFILE_FAIL";

export const GET_USER_PROFILE_START = "GET_USER_PROFILE_START";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

// PASSWORD
export const PASSWORD_CHANGE_START = "PASSWORD_CHANGE_START";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";

// ADDRESS 
export const ADD_NEW_ADDRESS_START = "ADD_NEW_ADDRESS_START";
export const ADD_NEW_ADDRESS_SUCCESS = "ADD_NEW_ADDRESS_SUCCESS";
export const ADD_NEW_ADDRESS_FAIL = "ADD_NEW_ADDRESS_FAIL";

export const GET_ADDRESS_START = "GET_ADDRESS_START";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL";

export const REMOVE_ADDRESS = "REMOVE_ADDRESS";

